"""empty message

Revision ID: 537555e77ef7
Revises: f755e70d1dc3
Create Date: 2024-04-01 14:34:19.552786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537555e77ef7'
down_revision = 'f755e70d1dc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_constraint('property_address_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.create_unique_constraint('property_address_key', ['address'])

    # ### end Alembic commands ###
