"""empty message

Revision ID: 6ce1807ebdc5
Revises: 2a3017b71cb3
Create Date: 2024-04-03 01:02:23.560519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ce1807ebdc5'
down_revision = '2a3017b71cb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.drop_constraint('worker_address_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.create_unique_constraint('worker_address_key', ['address'])

    # ### end Alembic commands ###
