"""empty message

Revision ID: 7cc0c234e0f1
Revises: 10e0d207a8ce
Create Date: 2024-04-07 22:48:12.875464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cc0c234e0f1'
down_revision = '10e0d207a8ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate', sa.Integer(), nullable=True))
        batch_op.drop_column('Rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Rate', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('rate')

    # ### end Alembic commands ###
