"""empty message

Revision ID: af399c50caf7
Revises: 53c5433fb060
Create Date: 2024-04-05 22:27:17.782473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af399c50caf7'
down_revision = '53c5433fb060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker2')
    op.drop_table('property2')
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_constraint('property_img_key', type_='unique')
        batch_op.drop_constraint('property_name_key', type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_billing_key', type_='unique')
        batch_op.drop_constraint('user_email_key', type_='unique')
        batch_op.drop_constraint('user_phone_key', type_='unique')

    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.drop_constraint('worker_banking_info_key', type_='unique')
        batch_op.drop_constraint('worker_email_key', type_='unique')
        batch_op.drop_constraint('worker_full_name_key', type_='unique')
        batch_op.drop_constraint('worker_img_key', type_='unique')
        batch_op.drop_constraint('worker_phone_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.create_unique_constraint('worker_phone_key', ['phone'])
        batch_op.create_unique_constraint('worker_img_key', ['img'])
        batch_op.create_unique_constraint('worker_full_name_key', ['full_name'])
        batch_op.create_unique_constraint('worker_email_key', ['email'])
        batch_op.create_unique_constraint('worker_banking_info_key', ['banking_info'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_phone_key', ['phone'])
        batch_op.create_unique_constraint('user_email_key', ['email'])
        batch_op.create_unique_constraint('user_billing_key', ['billing'])

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.create_unique_constraint('property_name_key', ['name'])
        batch_op.create_unique_constraint('property_img_key', ['img'])
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    op.create_table('property2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('worker_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['worker2.id'], name='property2_worker_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='property2_pkey'),
    sa.UniqueConstraint('name', name='property2_name_key')
    )
    op.create_table('worker2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='worker2_pkey'),
    sa.UniqueConstraint('email', name='worker2_email_key'),
    sa.UniqueConstraint('full_name', name='worker2_full_name_key')
    )
    # ### end Alembic commands ###
