"""empty message

<<<<<<< HEAD:migrations/versions/1104408ad2ec_.py
<<<<<<<< HEAD:migrations/versions/8499a4e15fbd_.py
Revision ID: 8499a4e15fbd
Revises: 
Create Date: 2024-04-05 15:14:08.002450
========
Revision ID: 1104408ad2ec
Revises: 
Create Date: 2024-04-07 20:39:13.631716
>>>>>>>> ac4331016b69c8b9a7f68442a4cceaa83d18461b:migrations/versions/1104408ad2ec_.py
=======
Revision ID: e63125723749
Revises: 
Create Date: 2024-04-08 14:30:12.557984
>>>>>>> 00b37ec1ac04f67ce02fa4759fc521b11b6204cd:migrations/versions/e63125723749_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:migrations/versions/1104408ad2ec_.py
<<<<<<<< HEAD:migrations/versions/8499a4e15fbd_.py
revision = '8499a4e15fbd'
========
revision = '1104408ad2ec'
>>>>>>>> ac4331016b69c8b9a7f68442a4cceaa83d18461b:migrations/versions/1104408ad2ec_.py
=======
revision = 'e63125723749'
>>>>>>> 00b37ec1ac04f67ce02fa4759fc521b11b6204cd:migrations/versions/e63125723749_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('img', sa.String(length=300), nullable=True),
    sa.Column('billing', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('default_city', sa.String(length=120), nullable=True),
    sa.Column('img', sa.String(length=300), nullable=True),
    sa.Column('banking_info', sa.String(length=300), nullable=True),
    sa.Column('ranking', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('beds', sa.Integer(), nullable=False),
    sa.Column('bath', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(length=10000), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('date_needed', sa.String(length=120), nullable=False),
    sa.Column('special_note', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=300), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=120), nullable=True),
    sa.Column('review', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    op.drop_table('schedule')
    op.drop_table('listing')
    op.drop_table('property')
    op.drop_table('worker')
    op.drop_table('user')
    # ### end Alembic commands ###
