"""empty message

Revision ID: f755e70d1dc3
Revises: 2e664f19f01d
Create Date: 2024-04-01 02:32:23.895211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f755e70d1dc3'
down_revision = '2e664f19f01d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_constraint('property_city_key', type_='unique')
        batch_op.drop_constraint('property_state_key', type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('billing',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
        batch_op.drop_constraint('user_address_key', type_='unique')
        batch_op.drop_constraint('user_img_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_img_key', ['img'])
        batch_op.create_unique_constraint('user_address_key', ['address'])
        batch_op.alter_column('billing',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.create_unique_constraint('property_state_key', ['state'])
        batch_op.create_unique_constraint('property_city_key', ['city'])

    # ### end Alembic commands ###
